/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/drive.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/lock.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/mail.ts" />
/// <reference path="../../config/queue.ts" />
/// <reference path="../../config/redis.ts" />
